import type { SalesOrderListItem } from '@erp/shared';

export const salesOrderListData: SalesOrderListItem[] = [
  {
    moduleLabel: '销售订单',
    docNo: 'S202607080001',
    title: 'Acme 夏季风扇补货',
    status: 'purchasing',
    secondaryStatus: 'partial_forwarder_shipped',
    counterpartyName: 'Acme Trading',
    customerOrderNo: 'PO-ACME-20260708',
    storeName: '02 Libuys',
    orderDate: '2026-07-08',
    estimatedDeliveryDate: '2026-08-08',
    ownerName: 'Zoe',
    createdAt: '2026-07-08T09:00:00.000Z',
    detailHref: '/sales-orders/1',
    createdBy: 'Mia',
    approvalStatus: 'purchasing',
    fulfillmentStatus: 'partial_forwarder_shipped',
    receiptStatus: 'fully_paid',
    financeConfirmStatus: 'confirmed',
    hasAfterSales: true,
    sourceSummary: '报价 Q202607080001 / 询价 IQ202607080002',
  },
  {
    moduleLabel: '销售订单',
    docNo: 'S202607080002',
    title: 'Bravo 插座首单',
    status: 'pending_sales_manager_approval',
    secondaryStatus: 'pending_sales_manager_approval',
    counterpartyName: 'Bravo Retail',
    customerOrderNo: 'PO-BRAVO-001',
    storeName: 'Bravo Main',
    orderDate: '2026-07-07',
    estimatedDeliveryDate: '2026-08-15',
    ownerName: 'Leo',
    createdAt: '2026-07-07T08:30:00.000Z',
    detailHref: '/sales-orders/2',
    createdBy: 'Mia',
    approvalStatus: 'pending_sales_manager_approval',
    fulfillmentStatus: 'pending_sales_manager_approval',
    receiptStatus: 'deposit_received',
    financeConfirmStatus: 'pending',
    hasAfterSales: false,
    sourceSummary: 'DIRECT / 直建',
  },
  {
    moduleLabel: '销售订单',
    docNo: 'S202607080003',
    title: 'Acme 秋季灯具追单',
    status: 'purchasing',
    secondaryStatus: 'partial_shipped',
    counterpartyName: 'Acme Trading',
    customerOrderNo: 'PO-ACME-20260706',
    storeName: '03 Airport',
    orderDate: '2026-07-06',
    estimatedDeliveryDate: '2026-08-20',
    ownerName: 'Zoe',
    createdAt: '2026-07-06T13:15:00.000Z',
    detailHref: '/sales-orders/3',
    createdBy: 'Ivy',
    approvalStatus: 'purchasing',
    fulfillmentStatus: 'partial_shipped',
    receiptStatus: 'deposit_received',
    financeConfirmStatus: 'pending',
    hasAfterSales: false,
    sourceSummary: '报价 Q202607080003',
  },
];
