export {
  buildProductCodePreview,
  defaultProductCodeRule,
  defaultProductCodeRuleSet,
  defaultSalesProductCodeRule,
  describeProductCodeRule,
  normalizeProductCodeRule,
  productCodeCategoryCodeMap,
  productCodeRuleSegmentKeys,
  productCodeRuleSerialScopes,
  validateProductCodeRule,
  type ProductCodeRule,
  type ProductCodeRuleKind,
  type ProductCodeRuleSet,
  type ProductCodeRuleSegment,
} from '@erp/shared';
