import type { SampleListItem } from '@erp/shared';

export const sampleOrderListData: SampleListItem[] = [
  {
    moduleLabel: '样品单',
    docNo: 'SP202607080001',
    title: 'Acme 夏季风扇首版样品',
    status: 'pending_sampling',
    secondaryStatus: 'quote_confirmed',
    customerName: 'Acme Trading',
    createdBy: 'Mia',
    ownerName: 'Zoe',
    quoteNo: 'Q202607080001',
    isReplacement: false,
    isCancelled: false,
    createdAt: '2026-07-08T09:00:00.000Z',
    detailHref: '/samples/1',
  },
  {
    moduleLabel: '样品单',
    docNo: 'SP202607080002',
    title: 'Bravo 插座替代样品',
    status: 'sample_sent',
    secondaryStatus: 'replacement_v2',
    customerName: 'Bravo Retail',
    createdBy: 'Noah',
    ownerName: 'Liam',
    quoteNo: 'Q202607080002',
    isReplacement: true,
    isCancelled: false,
    createdAt: '2026-07-07T10:30:00.000Z',
    detailHref: '/samples/2',
  },
  {
    moduleLabel: '样品单',
    docNo: 'SP202607080003',
    title: 'Acme 灯具取消样品',
    status: 'canceled',
    secondaryStatus: 'cancel_recorded',
    customerName: 'Acme Trading',
    createdBy: 'Ivy',
    ownerName: 'Zoe',
    quoteNo: 'Q202607080003',
    isReplacement: false,
    isCancelled: true,
    createdAt: '2026-07-06T14:00:00.000Z',
    detailHref: '/samples/3',
  },
];
