import type { AfterSalesListItem } from '@erp/shared';

export const afterSalesListData: AfterSalesListItem[] = [
  {
    moduleLabel: '售后单',
    docNo: 'AS202607080001',
    title: 'Acme 风扇批量退款',
    status: 'processing',
    secondaryStatus: 'refund',
    createdAt: '2026-07-08T11:00:00.000Z',
    detailHref: '/after-sales/1',
    customerName: 'Acme Trading',
    supplierName: 'Acme Supply',
    createdBy: 'Mia',
    ownerName: 'Zoe',
    type: 'refund',
    financeReviewStatus: 'confirmed',
    receiptCollectionStatus: 'fully_paid',
    shipmentBatchNo: 'SB202607080001',
  },
  {
    moduleLabel: '售后单',
    docNo: 'AS202607080002',
    title: 'Bravo 插座客诉补发',
    status: 'pending_approval',
    secondaryStatus: 'customer_complaint',
    createdAt: '2026-07-07T16:00:00.000Z',
    detailHref: '/after-sales/2',
    customerName: 'Bravo Retail',
    supplierName: 'Bravo Industrial',
    createdBy: 'Mia',
    ownerName: 'Leo',
    type: 'customer_complaint',
    financeReviewStatus: 'pending',
    receiptCollectionStatus: 'deposit_received',
    shipmentBatchNo: 'SB202607080002',
  },
  {
    moduleLabel: '售后单',
    docNo: 'AS202607080003',
    title: 'Acme 灯具返工处理',
    status: 'processing',
    secondaryStatus: 'rework',
    createdAt: '2026-07-06T14:30:00.000Z',
    detailHref: '/after-sales/3',
    customerName: 'Acme Trading',
    supplierName: 'Acme Supply',
    createdBy: 'Ivy',
    ownerName: 'Zoe',
    type: 'rework',
    financeReviewStatus: 'pending',
    receiptCollectionStatus: 'unpaid',
    shipmentBatchNo: 'SB202607080003',
  },
];
