import type { PurchaseOrderListItem } from '@erp/shared';

export const purchaseOrderListData: PurchaseOrderListItem[] = [
  {
    moduleLabel: '采购单',
    docNo: 'P202607080001',
    title: 'Acme 风扇供应拆单',
    status: 'purchasing',
    secondaryStatus: 'partial_forwarder_shipped',
    supplierName: 'Acme Supply',
    ownerName: 'Zoe',
    createdAt: '2026-07-08T10:00:00.000Z',
    detailHref: '/purchase-orders/1',
    createdBy: 'Mia',
    approvalStatus: 'purchasing',
    fulfillmentStatus: 'partial_forwarder_shipped',
    salesOrderNo: 'S202607080001',
    isResubmitted: true,
  },
  {
    moduleLabel: '采购单',
    docNo: 'P202607080002',
    title: 'Bravo 插座首单采购',
    status: 'pending_purchase_manager_approval',
    secondaryStatus: 'pending_purchase_manager_approval',
    supplierName: 'Bravo Industrial',
    ownerName: 'Leo',
    createdAt: '2026-07-07T11:30:00.000Z',
    detailHref: '/purchase-orders/2',
    createdBy: 'Mia',
    approvalStatus: 'pending_purchase_manager_approval',
    fulfillmentStatus: 'pending_purchase_manager_approval',
    salesOrderNo: 'S202607080002',
    isResubmitted: false,
  },
  {
    moduleLabel: '采购单',
    docNo: 'P202607080003',
    title: 'Acme 灯具追加采购',
    status: 'purchasing',
    secondaryStatus: 'partial_shipped',
    supplierName: 'Acme Supply',
    ownerName: 'Zoe',
    createdAt: '2026-07-06T15:20:00.000Z',
    detailHref: '/purchase-orders/3',
    createdBy: 'Ivy',
    approvalStatus: 'purchasing',
    fulfillmentStatus: 'partial_shipped',
    salesOrderNo: 'S202607080003',
    isResubmitted: false,
  },
];
