export const QUOTE_STATUSES = [
  'draft',
  'submitted',
  'pending_boss_approval',
  'boss_approved',
  'inquiry_in_progress',
  'converted_to_quote',
  'pending_boss_price_confirmation',
  'pending_customer_feedback',
  'customer_accepted',
  'customer_no_follow_up',
  'repricing_in_progress',
  'quoted',
  'revised',
  'sample_requested',
  'ordered',
  'closed',
] as const;
