import type { QuoteListItem } from '@erp/shared';

export const quoteListData: QuoteListItem[] = [
  {
    moduleLabel: '报价单',
    docNo: 'Q202607080001',
    title: 'Acme 夏季风扇报价',
    status: 'quoted',
    secondaryStatus: 'boss_confirmed',
    documentType: 'quote',
    customerName: 'Acme Trading',
    customerId: 1,
    createdBy: 'Zoe',
    sourceType: 'expo',
    bossConfirmed: true,
    createdAt: '2026-07-08T09:00:00.000Z',
    detailHref: '/quotes/1',
  },
  {
    moduleLabel: '报价单',
    docNo: 'Q202607080002',
    title: 'Bravo 插座首单报价',
    status: 'quoted',
    secondaryStatus: 'pending_boss_confirmation',
    documentType: 'quote',
    customerName: 'Bravo Retail',
    createdBy: 'Leo',
    sourceType: 'website',
    bossConfirmed: false,
    createdAt: '2026-07-07T10:30:00.000Z',
    detailHref: '/quotes/2',
  },
  {
    moduleLabel: '需求单',
    docNo: 'XQ202607080003',
    title: 'Acme 秋季灯具需求单',
    status: 'revised',
    secondaryStatus: 'revision_pending',
    documentType: 'demand',
    customerName: 'Acme Trading',
    customerId: 1,
    createdBy: 'Zoe',
    sourceType: 'referral',
    bossConfirmed: false,
    createdAt: '2026-07-06T14:00:00.000Z',
    detailHref: '/quotes/3',
  },
];
